"""
SFT distillation script: train a smaller model to reproduce outputs
generated by a larger teacher model.

Loads teacher-generated datasets from one or more data source directories
(e.g. damaged_datasets_reasoning/, damaged_datasets_reasoning_sample/) and
trains the student to produce the same output given (input, damage_level).

Usage:
    python train_sft.py --dataset rose --teacher_model llama70b --prompt_type few_shot --exclude_splits=rose_cnndm_validation
    python train_sft.py --dataset rose --data_sources reasoning,reasoning_sample  # combine two sources
    python train_sft.py --dataset cus_qa --teacher_model llama70b --exclude_splits=qa_cz_en
    python train_sft.py --config trained_models/rose/.../run_config.json
"""

import argparse
import json
import logging
import os
import warnings
from pathlib import Path
from typing import Dict, List

os.environ["UNSLOTH_VLLM_STANDBY"] = "1"

from transformers.trainer_utils import get_last_checkpoint
from unsloth import FastLanguageModel
from unsloth.chat_templates import train_on_responses_only
from trl import SFTConfig, SFTTrainer


from datasets import Dataset

from human_feedback_datasets.processed_dataset import ProcessedDataset
from human_feedback_datasets.prompts import (
    CUS_QA_ZERO_SHOT_PROMPT,
    MOCHA_ZERO_SHOT_PROMPT,
    ROSE_ZERO_SHOT_PROMPT,
    WMT_ZERO_SHOT_PROMPT,
)

# ---------------------------------------------------------
# SETUP & LOGGING
# ---------------------------------------------------------
os.environ.setdefault("TF_FORCE_GPU_ALLOW_GROWTH", "true")

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.INFO)
logging.getLogger("pytorch_lightning").setLevel(logging.WARNING)
warnings.filterwarnings("ignore", category=UserWarning)

# ---------------------------------------------------------
# GLOBALS & TEMPLATES
# ---------------------------------------------------------
ROSE_USER_TEMPLATE = "source_text: {source}\nreference_summary: {reference}\ndamage_level: {damage_level}"
MOCHA_USER_TEMPLATE = "passage: {context}\nquestion: {source}\ninput_answer: {reference}\ndamage_level: {damage_level}"
CUS_QA_USER_TEMPLATE = "question: {source}\ninput_answer: {reference}\ndamage_level: {damage_level}"
WMT_USER_TEMPLATE = "source_sentence: {source}\nreference_translation: {reference}\ndamage_level: {damage_level}"

DATASET_CONFIG = {
    "rose": (ROSE_ZERO_SHOT_PROMPT, ROSE_USER_TEMPLATE),
    "cus_qa": (CUS_QA_ZERO_SHOT_PROMPT, CUS_QA_USER_TEMPLATE),
    "mocha": (MOCHA_ZERO_SHOT_PROMPT, MOCHA_USER_TEMPLATE),
    "wmt": (WMT_ZERO_SHOT_PROMPT, WMT_USER_TEMPLATE),
}

BASE_DATA_DIR = Path("/mnt/proj1/fta-25-74/dev/master_thesis/src/karolina_testing")

# Short aliases → actual directory names under BASE_DATA_DIR
DATA_SOURCE_ALIASES = {
    "reasoning":        "damaged_datasets_reasoning",
    "reasoning_sample": "damaged_datasets_reasoning_sample",
    "no_reasoning":     "damaged_datasets",
    "fixed":            "damaged_datasets_fixed",
    "wmt_extra":        "damaged_datasets_wmt",
}

DEFAULT_DATA_SOURCES = ["no_reasoning"]


# ---------------------------------------------------------
# HELPER FUNCTIONS
# ---------------------------------------------------------
def resolve_data_sources(source_specs: List[str]) -> List[Path]:
    """Resolve short aliases or absolute paths to actual directories."""
    dirs = []
    for spec in source_specs:
        if spec in DATA_SOURCE_ALIASES:
            dirs.append(BASE_DATA_DIR / DATA_SOURCE_ALIASES[spec])
        else:
            p = Path(spec)
            if p.is_absolute():
                dirs.append(p)
            else:
                dirs.append(BASE_DATA_DIR / spec)
    return dirs


def load_damaged_datasets(
    dataset_name: str,
    teacher_model: str,
    data_source_dirs: List[Path],
    prompt_type: str = "few_shot",
    split: str = None,
    exclude_splits: List[str] = None,
) -> ProcessedDataset:
    """Load teacher-generated dataset files from one or more source directories.

    Args:
        dataset_name: Domain name (rose, mocha, cus_qa, wmt).
        teacher_model: Teacher model id (llama70b, llama4scout, qwen3_30b).
        data_source_dirs: Resolved list of base directories to search.
        prompt_type: Prompt variant used during generation (few_shot / zero_shot).
        split: If given, load only this split (e.g. 'rose_cnndm_test', 'qa_cz_en').
        exclude_splits: List of split names to skip (e.g. eval splits like 'rose_cnndm_validation').
    """
    if split:
        pattern = f"dataset_{split}_{teacher_model}_{prompt_type}.jsonl"
    else:
        pattern = f"*_{teacher_model}_{prompt_type}.jsonl"

    # Collect matching files across all source directories
    files = []
    for base_dir in data_source_dirs:
        ds_dir = base_dir / dataset_name
        if not ds_dir.exists():
            print(f"  WARNING: directory not found, skipping: {ds_dir}")
            continue
        matched = sorted(ds_dir.glob(pattern))
        for f in matched:
            print(f"  Found: {f.relative_to(BASE_DATA_DIR)}")
        files.extend(matched)

    # Filter out evaluation splits
    if exclude_splits:
        before = len(files)
        files = [
            f for f in files
            if not any(f"dataset_{es}_{teacher_model}" in f.name for es in exclude_splits)
        ]
        if before != len(files):
            print(f"  Excluded {before - len(files)} eval-split file(s): {exclude_splits}")

    if not files:
        raise FileNotFoundError(
            f"No files matching '{pattern}' in {[str(d / dataset_name) for d in data_source_dirs]} "
            f"(after exclusions)"
        )

    combined = ProcessedDataset()
    for f in files:
        print(f"  Loading: {f.relative_to(BASE_DATA_DIR)}")
        combined = combined + ProcessedDataset.load(f)
    return combined


def to_sft_format(dataset: ProcessedDataset, system_prompt: str, user_template: str, tokenizer) -> Dict[str, List[str]]:
    """Format damaged dataset for SFT. Target = prediction (teacher's damaged output)."""
    texts = []

    for data in dataset:
        user_content = user_template.format(
            context=data.context if data.context else "",
            source=data.input,
            reference=data.reference,
            damage_level=data.processed_human_score,
        )

        # Distillation target: the teacher model's damaged output
        target_content = data.prediction

        conversation = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
            {"role": "assistant", "content": target_content},
        ]

        text = tokenizer.apply_chat_template(
            conversation,
            tokenize=False,
            add_generation_prompt=False,
        )
        texts.append(text)

    return {"text": texts}


# ---------------------------------------------------------
# ARGUMENT PARSER
# ---------------------------------------------------------
def parse_args():
    parser = argparse.ArgumentParser(description="SFT Distillation Script")
    parser.add_argument(
        "--config", type=str, default=None,
        help="Path to a run_config.json from a previous run. "
        "All settings are loaded from the file; any additional CLI flags override them.",
    )
    parser.add_argument("--model", type=str, default="unsloth/Llama-3.2-1B-Instruct", help="Student model name or path")
    parser.add_argument("--dataset", type=str, choices=["rose", "cus_qa", "mocha", "wmt"], default="rose")
    parser.add_argument("--teacher_model", type=str, default="llama70b",
                        choices=["llama70b", "llama4scout", "qwen3_30b"],
                        help="Teacher model whose damaged outputs to distill from")
    parser.add_argument("--data_sources", type=str, default=",".join(DEFAULT_DATA_SOURCES),
                        help="Comma-separated list of data source aliases or absolute paths. "
                             f"Aliases: {', '.join(DATA_SOURCE_ALIASES.keys())}. "
                             "Example: 'reasoning,reasoning_sample' to combine both.")
    parser.add_argument("--output_dir", type=str, default=None)
    parser.add_argument("--max_seq_length", type=int, default=2048)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--grad_accum", type=int, default=2)
    parser.add_argument("--run_name", type=str, default=None)
    parser.add_argument("--split", type=str, default=None,
                        help="Dataset split to load, e.g. 'rose_cnndm_test', 'qa_cz_en'. "
                             "If omitted, all splits for the dataset are combined.")
    parser.add_argument("--prompt_type", type=str, default="few_shot",
                        choices=["few_shot", "zero_shot"],
                        help="Teacher prompt variant to distill from (default: few_shot)")
    parser.add_argument("--exclude_splits", type=str, default=None,
                        help="Comma-separated list of splits to exclude (e.g. eval splits). "
                             "Example: 'rose_cnndm_validation,rose_xsum'")
    parser.add_argument(
        "--resume_from_checkpoint", type=str, default='latest',
        help="Path to a checkpoint directory to resume from, or 'latest' to auto-detect.",
    )

    preliminary, _ = parser.parse_known_args()
    if preliminary.config:
        config_path = Path(preliminary.config)
        if not config_path.exists():
            parser.error(f"Config file not found: {config_path}")
        with open(config_path) as f:
            saved = json.load(f)
        print(f"Loaded config from: {config_path}")

        config_keys = {"model", "dataset", "teacher_model", "data_sources", "split",
                       "prompt_type", "exclude_splits", "output_dir", "max_seq_length",
                       "epochs", "batch_size", "grad_accum", "run_name"}
        defaults = {k: v for k, v in saved.items() if k in config_keys}

        if preliminary.resume_from_checkpoint is None:
            defaults["resume_from_checkpoint"] = "latest"

        parser.set_defaults(**defaults)

    return parser.parse_args()


# ---------------------------------------------------------
# MAIN EXECUTION
# ---------------------------------------------------------
def main():
    args = parse_args()

    # --- DYNAMIC FOLDER NAMING ---
    short_model_name = args.model.rstrip("/").split("/")[-1]
    sources_tag = "-".join(s.strip() for s in args.data_sources.split(","))
    folder_name = f"{short_model_name}_sft_distill_{args.teacher_model}_{args.prompt_type}_{sources_tag}"
    if args.split:
        folder_name = f"{folder_name}_{args.split}"
    if args.run_name:
        folder_name = f"{folder_name}_{args.run_name}"

    if args.output_dir:
        base_out_dir = Path(args.output_dir)
    else:
        base_out_dir = Path("models_trained") / args.dataset / folder_name
    base_out_dir.mkdir(parents=True, exist_ok=True)

    exclude_splits = [s.strip() for s in args.exclude_splits.split(",")] if args.exclude_splits else None
    data_source_specs = [s.strip() for s in args.data_sources.split(",")]
    data_source_dirs = resolve_data_sources(data_source_specs)

    print("--- Starting SFT Distillation Training ---")
    print(f"Student model:  {args.model}")
    print(f"Teacher model:  {args.teacher_model}")
    print(f"Prompt type:    {args.prompt_type}")
    print(f"Data sources:   {data_source_specs}")
    print(f"Dataset:        {args.dataset}")
    if args.split:
        print(f"Split:          {args.split}")
    if exclude_splits:
        print(f"Exclude splits: {exclude_splits}")
    print(f"Output:         {base_out_dir}")
    print("-------------------------------------------\n")

    # --- SAVE CONFIG EARLY ---
    def _save_run_config(save_dir: Path):
        run_config = {
            "model": args.model,
            "dataset": args.dataset,
            "teacher_model": args.teacher_model,
            "data_sources": args.data_sources,
            "prompt_type": args.prompt_type,
            "split": args.split,
            "exclude_splits": args.exclude_splits,
            "output_dir": str(base_out_dir),
            "max_seq_length": args.max_seq_length,
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "grad_accum": args.grad_accum,
            "run_name": args.run_name,
        }
        with open(save_dir / "run_config.json", "w") as f:
            json.dump(run_config, f, indent=2, default=str)

    _save_run_config(base_out_dir)

    # --- SKIP IF ALREADY TRAINED ---
    final_save_path = base_out_dir / f"{folder_name}_final_model"
    if final_save_path.exists():
        print(f"Final model already exists at {final_save_path}, skipping training.")
        return

    # --- MODEL LOADING ---
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.model,
        max_seq_length=args.max_seq_length,
        load_in_4bit=False,
        load_in_8bit=False,
    )

    # --- LORA CONFIG ---
    model = FastLanguageModel.get_peft_model(
        model,
        r=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=32,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    # --- DATASET LOADING ---
    sys_prompt, user_tmpl = DATASET_CONFIG[args.dataset]

    print(f"Loading datasets from: {[str(d) for d in data_source_dirs]}")
    raw_dataset = load_damaged_datasets(
        args.dataset, args.teacher_model,
        data_source_dirs=data_source_dirs,
        prompt_type=args.prompt_type,
        split=args.split,
        exclude_splits=exclude_splits,
    )

    # Format for SFT (target = teacher's damaged prediction)
    formatted_data_dict = to_sft_format(raw_dataset, sys_prompt, user_tmpl, tokenizer)
    dataset = Dataset.from_dict(formatted_data_dict)

    print(f"Dataset Size: {len(dataset)} examples\n")

    # --- TRAINING CONFIG ---
    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=dataset,
        args=SFTConfig(
            per_device_train_batch_size=args.batch_size,
            gradient_accumulation_steps=args.grad_accum,
            warmup_steps=5,
            num_train_epochs=args.epochs,
            learning_rate=2e-4,
            logging_steps=1,
            optim="adamw_8bit",
            weight_decay=0.001,
            lr_scheduler_type="linear",
            seed=3407,
            output_dir=str(base_out_dir),
            save_strategy="steps",
            save_steps=200,
            # save_total_limit=10,
            # report_to="wandb",
            run_name=args.run_name,
            # max_seq_length=args.max_seq_length,
        ),
    )

    # --- RESPONSE MASKING ---
    # Detect model family to pick correct chat-template delimiters
    model_type = getattr(getattr(model, "config", None), "model_type", "").lower()
    is_gemma = "gemma" in model_type or "gemma" in args.model.lower()
    if is_gemma:
        instruction_part = "<start_of_turn>user\n"
        response_part = "<start_of_turn>model\n"
    else:  # Llama-style
        instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n"
        response_part = "<|start_header_id|>assistant<|end_header_id|>\n\n"

    trainer = train_on_responses_only(
        trainer,
        instruction_part=instruction_part,
        response_part=response_part,
    )

    # --- TRAIN & SAVE ---
    resume = args.resume_from_checkpoint
    if resume == "latest":
        resume = get_last_checkpoint(base_out_dir)  # None if no checkpoint exists
    trainer.train(resume_from_checkpoint=resume)

    model.save_pretrained(str(final_save_path))
    tokenizer.save_pretrained(str(final_save_path))
    _save_run_config(final_save_path)

    print(f"\nSFT Distillation complete! Saved to: {final_save_path}")


if __name__ == "__main__":
    main()
