[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "master_thesis"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
